config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'tops#index'

    resources :tops
    resources :users, only: [:show, :edit, :update]
    resources :buys, only: :create

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy.rb
class Buy < ApplicationRecord
    belongs_to :user, optional: true
    
    validates_presence_of :user_id, :bought, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/top.rb
class Top < ApplicationRecord
    has_many :buys
end

app/models/user.rb
class User < ApplicationRecord
  
  mount_uploader :image, ImageUploader

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :buys
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:text])
    devise_parameter_sanitizer.permit(:account_update, keys: [:image])
    
  end
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController

    def create
        #top.idを配列で補填
        @contents = create_buy
        @content = @contents.values.last(1).flatten
        @con = @content.map{ |num| num.to_i }
        
        #Buyにuser_nicknameとbought(grocery)を保存 [top.id を元に]
        @co = @con.map{ |id| Top.find(id) }
        @do = @co.pluck(:grocery)
        Buy.create(user_id: create_buy[:user_id], bought: @do)
        
        #選択したhashに対応するtop.idを削除
        @co = @con.map{ |id| Top.find(id) }
        @co.each{ |i| 
        @c = i
        @c.destroy
        }
        
        redirect_to :root and return
    end
    
    private
    def create_buy
        params.require(:buy).permit(:user_id,bought: [])
    end
end

app/controllers/ivents_controller.rb
class IventsController < ApplicationController
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
    
    def create
        Purchase.create(create_purchase)
        redirect_to :root and return
    end
    
    private
    def create_purchase
        params.permit(purchased: [])
        binding.pry
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def index
        # ①投稿機能
        @top = Top.new
        
        # ②食材選択リスト
        @year = Time.current.year
        @month = Time.current.month
        @day = Time.current.day
        
        @buy = Buy.new
        @tops = Top.order("created_at DESC")
        @users = User.all
        
        # ③購入リスト
        @bought = Buy.order('created_at DESC').limit(3)
        
        # ④ランキング機能
        search_date = '@year-@month-@date'  #現在の"年-月-日"を設定
        this_month = Buy.where(created_at: search_date.in_time_zone.all_month)  #今年の今月のデータを抽出
        purchase = this_month.group(:user_id).order('count_user_id DESC').limit(5).count(:user_id)
        @purchased_numbers = purchase.values
        @rankings = purchase.keys.map { |id| User.find(id) }
        
    end
    
    def create
        Top.create(create_top)
        redirect_to :root and return
    end
    
    def destroy
        delete = Top.find(params[:id])
        delete.destroy
        redirect_to :root and return
    end
    
    def edit
        @edit = Top.find(params[:id])
    end
    
    def update
        edited = Top.find(params[:id])
        edited.update(update_top)
        redirect_to :root
    end
    
    private
    def create_top
        params.require(:top).permit(:grocery, :number)
    end
    
    def update_top
        params.permit(:grocery, :number)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
    
    def edit
    end
    
    def update
        current_user.update(update_params)
    end
    
    private
    def update_params
        params.require(:user).permit(:nickname, :full_name, :text, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/ivents_helper.rb
module IventsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharehouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
    <header class="header">
      <div class="header-main">
        <h1><a class ="header-name"href="/">上賀茂ハウス</a></h1>
      </div>
   	  <% if user_signed_in? %>
     	<div class="header-sub">
     		<ul>
      	  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'post' %></li>
      		<li><%= link_to "マイページ", edit_user_path(current_user), class: 'post' %></li>
        </ul>
      </div>
     	<% else %>
     	<div class="header-sub">
     		<ul>
     		  <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
     		  <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
     		</ul>
    	</div>
      <% end %>
    </header>
  
    <%= yield %>
    </div>
  
    <footer>
      <p>borderlesshouse</p>
      <p>-京都上賀茂-</p>
    </footer>
  </body>
</html>

app/views/tops/edit.html.erb
<div class ="all_contents">
  <div class ="contents edit_grocery">
    <div class="new_grocery">
      <%= form_for @edit do %>
      <h3>
        編集する
      </h3>
      <input type="text" name="grocery" value="<%= @edit.grocery %>" placeholder="何が足りない？" autofocus="true">
      <input type="text" name="number" value="<%= @edit.number %>" placeholder="何個？" autofocus:"true">
      <input type="submit" value="変更">
      <% end %>
    </div>
  </div>
</div>

app/views/tops/index.html.erb
<div class ="all_contents">
  <div class ="new_grocery">
    <%= form_for(@top) do |f| %>
      <%= f.text_field :grocery, placeholder: "何が足りない？" %>
      <%= f.text_field :number, placeholder: "いくつ？" %>
      <%= f.submit "投稿する" %>
    <% end %>
  </div>
  
  <div class ="contents clearfix">   <!-- clearfix のクラスもここで定義！！   -->
    <div class ="left_content">
      
    <!-- ①食材選択リスト -->
    <div class ="form">
    <%= form_for(@buy, url: buys_path, method: :post) do |f| %>
      <div class ="field_top">
        <span><%= "#{@month}/#{@day}" %></span></br>
        <%= f.label :bought, "【購入リスト】" %>
        <br>
        <ul>
        <% @tops.each do |top| %>
        <%= f.check_box :bought, {multiple: true}, top.id, nil %>
        <a href="/tops/<%= top.id %>/edit" ><%= "#{top.grocery}　:　#{top.number}" %></a>
        <a href="/tops/<%= top.id %>" data-method="delete" class ="delete" onclick="return confirm('本当に削除しますか？')" >削除</a>
        <br>
        <% end %>
        </ul>
     </div>
     
      <!-- userも同時選択 -->
        <%= f.select :user_id, User.all.map { |user| [user.nickname, user.id] } %>
          <div class="form-group">
            <%= f.submit '購入', class: 'btn btn-primary btn-block' %>
          </div>
    <% end %>
    </div>
    <hr>
   
    <!-- ③購入物一覧  -->
    <div class ="bought">
      <% @bought.each do |bou| %>
        <div class="bought_box">
          <p><%= "#{bou.bought}" %><span><%= " #{time_ago_in_words bou.created_at}前" %></span></p>
          <p class="bought_name"><%= "　→ " %><a href="/users/<%= "#{bou.user_id}" %>"><%= "#{bou.user.nickname}" %></a><%= "が購入" %></p>
        </div>
      <% end %>
    </div>
    
    </div>
    
    <!-- ④ランキング機能 -->
    <div class ="right_content">
      <h2><%= "#{@month}" %>月 購入ランキング</h2>
        <div class ="inner_rank">
          <% num = 1 %>
          <% @rankings.zip(@purchased_numbers) do |rank,number| %>
          <p>
          <%= "#{num}" %>位
          <img src="<%= "#{rank.image}" %>"
               onerror="this.src='/uploads/user/image/no-image-3.png'">
          <a href="/users/<%= "#{rank.id}" %>"><%= "#{rank.nickname}" %></a><br>
          <span>[<%="#{number}" %>回購入]</span>
          </p>
          <% num += 1 %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="all_contents">
  <div class="out_contents">
    <div class="user_show">
      <div class="user_out_box">
        <div class="user_in_box">
    <%= form_for current_user do |f| %>
    
    <div class="user_edit_image" >
      <img src="<%= "#{current_user.image}" %>"
           onerror="this.src='/uploads/user/image/no-image-3.png'">
    </div>
    
    <div class="image">
      <%= f.file_field :image %>
    </div>

    <div class="field">
      <%= f.label :nickname, "ニックネーム" %> <em>(6字以内)</em><br />
      <%= f.text_field :nickname, autofocus: true, maxlength: "6" %>
    </div>
    
    <div class="field">
      <%= f.label :full_name, "フルネーム" %><br/>
      <%= f.text_field :full_name, placeholder: "-", class: "form-control" %>
    </div>
    
    <div class="field">
      <%= f.label :text, "紹介文" %>
      <%= f.text_area :text, placeholder: "-" ,size: "30x5" ,class: "form-control" %>
    </div>
    
    <div class="btn_user_edit">
        <%= f.submit "編集", class: "btn btn-primary withripple" %>
    </div>
    
  <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="all_contents">
  <div class="out_contents">
    <div class="user_show">
      <div class="user_out_box">
      
        <div id="photo">
          <img src="<%= "#{@user.image}" %>"
               onerror="this.src='/uploads/user/image/no-image-3.png'">
        </div>

        <h2><%= "#{@user.nickname}" %></h2>
        <span><%= "#{@user.full_name}" %></span>
        <section><紹介文></section>
        <p><%= "#{@user.text}" %></p>
    
      </div>
    
      <a href="/", class="home">ホームに戻る</a>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<div class="all_contents">
  <div class="out_contents">
    <div class="user_show">
      <div class="user_out_box">
        <div class="user_in_box">
          <h3>プロフィールの編集が完了しました。</h3>
          <%= link_to "ホームに戻る", root_path %>
        </div>
      </div>
    </div>
  </div>
</div>